export const MAKE_ORDER_REQUEST = "MAKE_ORDER_REQUEST";
export const MAKE_ORDER_SUCCESS = "MAKE_ORDER_SUCCESS";
export const MAKE_ORDER_ERROR = "MAKE_ORDER_ERROR";
export const RESET_ORDER = "RESET_ORDER";
